### ISSUE TITLE
cudamalloc dynamic matrix 

### ISSUE THREAD

**Issue by TyrionLanister** [GPMueller/eigen-cuda#1]
I was hoping to use a dynamic Eigen matrix on Cuda memory but it seems that  eigen only supports  c++ new for dynamic allocation of matrix hence cudamalloc/cudamallocmanaged doesnt work until i fix the size of rows, cols( as you have shown with Vector3d )

eg. 
```
Matrix<int, 6, 3, RowMajor> *in = (Matrix<int, 6, 3, RowMajor> *)malloc(sizeof(Matrix<int, 6, 3, RowMajor>));  // Works
Matrix<int, -1, -1, RowMajor> *in = (Matrix<int, -1, -1, RowMajor> *)malloc(sizeof(Matrix<int, -1, -1, RowMajor>(6,3))); // Doesnt work  
```
Do you know any other means to make it work

**Comment by GPMueller** [comment]
I'm not sure how one would achieve this directly with `Eigen` types, as you would need some re-allocation mechanism for whenever the size of your object changes. Maybe the following will help you nonetheless.

The only way I know so far (and which I currently use in some projects of mine) is to use `std::vector<Eigen::..., managed_allocator<Eigen::...>>`. See [here](https://github.com/GPMueller/vectorfield/blob/master/include/vectorfield.hpp) and [here](https://github.com/GPMueller/vectorfield/blob/master/include/managed_allocator.hpp) for an example how this can be done.
You could then for example have a (msize*3 x nsize*3) Matrix, i.e. msize rows by nsize columns of 3x3 blocks, for example like this:
```
auto matrices = std::vector<Eigen::Matrix3d, managed_allocator<Eigen::Matrix3d>>(msize*msize);
```
Note that the Matrices memory will all be contiguous in memory and if your ordering is correct you can create a reference (without copying the data!) to this unified memory object with something along the lines of
```
Eigen::Ref<Eigen::MatrixXd> x = Eigen::Map<Eigen::MatrixXd>(matrices[0].data(), 3*msize, 3*nsize);
```
See https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html and google for how to do this mapping properly, I didn't try this exact example (I only used this for vectors so far).

Just to clarify: in the example *vectorfield* code, you could use
```
auto vector_of_vectors = std::vector<Vector3, managed_allocator<Vector3>>(N);
Eigen::Ref<VectorX> single_vector = Eigen::Map<VectorX>(vector_of_vectors[0].data(), 3*N);
```

**Comment by TyrionLanister** [comment]
Well I tried a different approach in which I used global memory pointer structure allocated on cuda with 2 D Matrix  pointer as it's member variable. I placed the Matrix data in global memory. With a single thread(a  single grid), I thought of allocating the 2 d matrix  Map structure on heap  with  the  reference of global memory. But this approach also failed. I realized that the

1. Cuda Kernels don't support 2 dimensional matrix. Thrust, a very popular c++ template library has no support for 2 d matrix inside kernel 
2.  Eigen FAQ says that:
dynamic allocation is **not supported** in cuda kernel
of-course heap based dynamic matrix is not supported
`Matrix<int, -1,-1> *test  = new Matrix<int,-1,-1>(5,5) // Dont work`

But even the stack based fixed sized  dont work inside kernel
`Matrix<int, 5,5> test // dont work `

**Comment by TyrionLanister** [comment]
Well the above code works. The asserts were  never tested and I was relying on stupid printf without typecasting them with int.

So the above method of using single thread to store map structure of eigen at heap while keeping underlying data in global memory is more extensive.
The heap map structure only stores 8 byte of eigen matrix with data lying on device memory and another 8 byte for the pointer of structure  for cpu code to reference  which is stored on global memory.
